export default [
  {
    "metadata": {
      "height_gm": 1528,
      "origin_px": 1496,
      "origin_py": 1104,
      "ox": 0,
      "oy": 0,
      "scale_m2px": 32,
      "width_gm": 3131
    },
    "_id": "644891e273ee4a54330ac27c",
    "name": "1st_floor_유진",
    "description": "map generated by undefined at 2023-04-26T02:52:37.121Z",
    "version": 2,
    "created_at": "2023-04-26T02:52:39.997Z",
    "updated_at": "2024-01-24T08:24:05.926Z",
    "id": "644891e273ee4a54330ac27c"
  },
  {
    "metadata": {
      "height_gm": 1241,
      "origin_px": 1425,
      "origin_py": 770,
      "ox": 0,
      "oy": 0,
      "scale_m2px": 32,
      "width_gm": 2954
    },
    "_id": "6448920773ee4a54330ac325",
    "name": "2nd_floor_yujin",
    "description": "map generated by undefined at 2023-04-26T02:53:11.760Z",
    "version": 1,
    "created_at": "2023-04-26T02:53:16.578Z",
    "updated_at": "2023-04-26T02:53:16.578Z",
    "id": "6448920773ee4a54330ac325"
  },
  {
    "metadata": {
      "height_gm": 1723,
      "origin_px": 1547,
      "origin_py": 1040,
      "ox": 0,
      "oy": 0,
      "scale_m2px": 32,
      "width_gm": 3188
    },
    "_id": "6448a41973ee4a54330af998",
    "name": "3rd_floor_yujin",
    "description": "map generated by undefined at 2023-04-26T04:10:30.972Z",
    "version": 1,
    "created_at": "2023-04-26T04:10:36.989Z",
    "updated_at": "2023-04-26T04:10:36.989Z",
    "id": "6448a41973ee4a54330af998"
  },
  {
    "metadata": {
      "height_gm": 1628,
      "origin_px": 1537,
      "origin_py": 848,
      "ox": 0,
      "oy": 0,
      "scale_m2px": 32,
      "width_gm": 2997
    },
    "_id": "6448a44c73ee4a54330afa33",
    "name": "4th_floor_yujin",
    "description": "map generated by undefined at 2023-04-26T04:11:15.466Z",
    "version": 1,
    "created_at": "2023-04-26T04:11:19.168Z",
    "updated_at": "2023-04-26T04:11:19.168Z",
    "id": "6448a44c73ee4a54330afa33"
  },
  {
    "metadata": {
      "height_gm": 1733,
      "origin_px": 2592,
      "origin_py": 1270,
      "ox": -81.007301,
      "oy": -39.680656,
      "scale_m2px": 32,
      "width_gm": 3164
    },
    "_id": "65e83bbc3772bfbd5267acd7",
    "name": "99F_CSSD",
    "description": "map generated at 2024-03-06T09:47:40.426689",
    "version": 2,
    "created_at": "2024-03-06T09:47:40.895Z",
    "updated_at": "2024-03-06T09:48:50.067Z",
    "id": "65e83bbc3772bfbd5267acd7"
  }
]